# Don't re-download node_modules every time. Cache it
cache:
  paths:
    - node_modules/

validate:
  image: gramener/builderrors
  script: builderrors

deploy:
  stage: deploy
  only: [v1, release]
  script:
    - 'ssh ubuntu@gramener.com "
        cd /mnt/gramener/apps/comicgenv1;
        git checkout -- .;
        git pull;
        npm install;
        npm run build;
        sudo systemctl restart comicgenv1;
      "'
